site_name: Sounstracks Build Story
site_url: https://chasewoot04.github.io
theme:
  name: material
  features:
    - content.footnote.tooltips
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences  
  - pymdownx.blocks.caption
  - tables
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
   
